server:
  port: 9090
spring:
  application:
    name: car-loan-consumers
  config:
    location: classpath:application.yml
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        input:
          destination: event.proposal.saved
          group: create.consumer
          consumer:
            maxAttempts: 2
            concurrency: 3
      rabbit:
        default:
          consumer:
            bindQueue: false
            declareDlx: false
            declareExchange: false
            queueNameGroupOnly: true
            autoBindDlq: false
            republishToDlq: false
        binder:
          connection-name-prefix: consumers
  rabbitmq:
    host: localdocker.com
    virtual-host: /car-loan
    cache:
      channel:
        size: 5
        checkout-timeout: 5s
    username: guest
    password: guest
  liquibase:
    enabled: false
  datasource:
    initialization-mode: EMBEDDED
    url: jdbc:h2:mem:db;INIT=CREATE SCHEMA IF NOT EXISTS consumers
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
management:
  server:
    port: ${server.port}
  metrics:
    export:
      jmx:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
---
spring:
  profiles: cloud
  main:
    lazy-initialization: true
  h2:
    console:
      enabled: false
  liquibase:
    enabled: true
  datasource:
    # Set env SPRING_DATASOURCE_PASSWORD, SPRING_DATASOURCE_USERNAME
    url: jdbc:postgresql://_db._tcp.car-loan-database/notifications
    initialization-mode: NEVER
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    # Set env SPRING_RABBITMQ_HOST, SPRING_RABBITMQ_PASSWORD, SPRING_RABBITMQ_USERNAME
    virtual-host: /
    cache:
      channel:
        size: 10
        checkout-timeout: 2s