server:
  port: 8080
spring:
  application:
    name: car-loan-proposal
  config:
    location: classpath:application.yml
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        input:
          destination: event.vehicle.created
          group: update.proposal.vehicle-market-value
          consumer:
            maxAttempts: 2
            concurrency: 3
        output:
          destination: event.proposal.saved
      rabbit:
        bindings:
          input:
            consumer:
              prefetch: 10
        default:
          consumer:
            bindQueue: false
            declareDlx: false
            declareExchange: false
            queueNameGroupOnly: true
            autoBindDlq: false
            republishToDlq: false
        binder:
          connection-name-prefix: loan-proposal
  rabbitmq:
    host: localdocker.com
    virtual-host: /car-loan
    cache:
      channel:
        size: 10
        checkout-timeout: 5s
    username: loan-proposal
    password: 12345678
  liquibase:
    enabled: false
  datasource:
    initialization-mode: EMBEDDED
    url: jdbc:h2:mem:db;INIT=CREATE SCHEMA IF NOT EXISTS proposal
    username: sa
    password: ""
    data: classpath:data-h2.sql
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
management:
  server:
    port: 9090
  metrics:
    export:
      jmx:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
---
spring:
  profiles: cloud
  main:
    lazy-initialization: true
  h2:
    console:
      enabled: false
  liquibase:
    enabled: true
  datasource:
    # Set env SPRING_DATASOURCE_PASSWORD, SPRING_DATASOURCE_USERNAME
    url: jdbc:postgresql://_db._tcp.car-loan-database/notifications
    initialization-mode: NEVER
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    # Set env SPRING_RABBITMQ_HOST, SPRING_RABBITMQ_PASSWORD, SPRING_RABBITMQ_USERNAME
    virtual-host: /
    cache:
      channel:
        size: 10
        checkout-timeout: 2s